name: recreate progress file

on: [push]

jobs: 
  create_progress_file:
    if: "contains(github.event.head_commit.message, '#')"
    name: re-create progress file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: delete file
        run: |
          rm -Rf progress.md
         
      - name: create file
        run: | 
          echo "```mermaid
          echo "gantt" > progress.md
          echo "    title Progress Diagram" >> progress.md
          echo "    dateFormat  YYYY-MM-DD" >> progress.md
          echo "    section Webshop basic" >> progress.md
          echo "    1 Introduction: i1, 2023-04-29, 2023-04-30" >> progress.md
          echo "    2 HTML intro: i2, after i1,  2d" >> progress.md
          echo "    3 CSS intro: i3, 2023-04-30, 2d" >> progress.md
          echo "```" >> progress.md
          
      - name: show file
        run: "cat progress.md"
      
      - name: show commits with Hash
        run: |
          for (commit in ${{github.event.commits}}); do
            if [[ ${commit.message} == *"#"* ]]; then
              echo "${commit.message}"
            fi
          done
   
      - name: Commit and push the file
        uses: maxgfr/github-commit-push-file@main
        with:
          commit_name: 'updated progress.md'
